FROM ubuntu:22.04

RUN apt-get update && apt-get install --force-yes -y --no-install-recommends \
    build-essential \
    sudo \
    cmake \
    gcc-arm-linux-gnueabihf \
    g++-arm-linux-gnueabihf